#ifndef GROUP_OSCORE_TEST_CLIENT_CONF_H_
#define GROUP_OSCORE_TEST_CLIENT_CONF_H_

#define CONTEXT_NUM 5
#define TOKEN_SEQ_NUM 5
#define EP_CTX_NUM 5

#define MSGS_TO_VERIFY_SIZE 3
#define MSGS_TO_SIGN_SIZE 3

#endif /* GROUP_OSCORE_TEST_CLIENT_CONF_H_ */
