CONTIKI_PROJECT = border-router
all: $(CONTIKI_PROJECT)
CONTIKI = ../..

# The BR is either native or embedded, and in the latter case must support SLIP
PLATFORMS_EXCLUDE = nrf52dk z1

# Include (Modified) RPL BR module
MODULES_REL += rpl-border-router
# Include webserver module
MODULES_REL += webserver
# Include optional target-specific module
include $(CONTIKI)/Makefile.identify-target
MODULES_REL += $(TARGET)


MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC
MODULES += os/net/routing/rpl-classic

#Multicast Engine
MODULES += os/net/ipv6/multicast

include $(CONTIKI)/Makefile.include
