include $(CONTIKI)/Makefile.identify-target

# Include BR variant depending on platform and also generic BR code for all
# embedded platforms
MODULES_REL += $(TARGET)

ifneq ($(TARGET),native)
	MODULES_REL += rpl-border-router/embedded
endif
